# Generated by Django 5.0.3 on 2024-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.FileField(blank=True, max_length=255, upload_to='files/dosage')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
