# Generated by Django 5.0.3 on 2024-03-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_order_cart_item_order_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
