# Generated by Django 5.0.3 on 2024-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cartitem_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosage',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_item',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='api.cartitem'),
        ),
    ]
