# Generated by Django 5.0.3 on 2024-03-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_quantity_dosage_qty_alter_order_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='api.dosage'),
        ),
    ]
