# Generated by Django 5.0.3 on 2024-03-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('On Delivery', 'On Delivery'), ('On Order', 'On Order')], max_length=20, null=True),
        ),
    ]
